---
title: "HW 5"
author: "Quyen Dang"
date: "11/7/2024"
output:
  pdf_document: default
  html_document:
    number_sections: yes
---

This homework is meant to give you practice in creating and defending a position with both statistical and philosophical evidence.  We have now extensively talked about the COMPAS ^[https://www.propublica.org/datastore/dataset/compas-recidivism-risk-score-data-and-analysis] data set, the flaws in applying it but also its potential upside if its shortcomings can be overlooked.  We have also spent time in class verbally assessing positions both for an against applying this data set in real life.  In no more than two pages ^[knit to a pdf to ensure page count] take the persona of a statistical consultant advising a judge as to whether they should include the results of the COMPAS algorithm in their decision making process for granting parole.  First clearly articulate your position (whether the algorithm should be used or not) and then defend said position using both statistical and philosophical evidence.  Your paper will be grade both on the merits of its persuasive appeal but also the applicability of the statistical and philosohpical evidence cited.  


In advising whether the COMPAS algorithm should inform parole decisions, I argue that it should not. Although COMPAS offers statistical assessments of relapsed risk, its use for parole eligibility is fraught with critical limitations. These limitations include statistical biases, undermining reliability, and significant ethical concerns about justice, fairness, and transparency. Relying on COMPAS could worsen the systematic inequalities within the criminal justice system. As a statistical consultant, I would advise that the potential harms of using COMPAS outweigh the algorithm’s benefits. 

COMPAS has demonstrated racial bias, inaccurately identifying risk levels in ways that disproportionately affect certain groups, especially Black defendants, compared to whites. Black defendants were nearly twice as likely as white defendants to be incorrectly classified as high-risk by COMPAS. This bias introduces a significant risk of unjust outcomes in parole decisions. Additionally, COMPAS has an accuracy rate of approximately 65%, which is only marginally better than a random guess. With an accuracy rate close to a 50-50 chance, COMPAS is almost as uncertain as flipping a coin when predicting who is likely to re-offend. The potential for errors makes it an unreliable choice for determining parole eligibility. Moreover, COMPAS’s methodology is not publicly accessible. Without transparency, neither judges nor defendants can fully evaluate the reliability of the risk scores it generates. This lack of transparency undermines accountability, which is essential for tools used in legal decision-making.
	
From a philosophical perspective, COMPAS conflicts with fundamental principles of justice and fairness. Philosopher John Rawl claims that inequalities should be structured to benefit the least advantage. A system like COMPAS, which statistically and disproportionately labels marginalized groups, directly contradicts this principle. By systematically disadvantaging these groups, COMPAS risks deepening the inequalities in the criminal justice system. Furthermore, COMPAS raises ethical issues about autonomy. An algorithm that statistically profiles individuals in a manner that reduces them to mere data points, rather than assessing them on unique circumstances, fails to respect the individual’s dignity. Using COMPAS scores to determine parole eligibility risks objectifying individuals as numbers rather than persons with potential for rehabilitation. Therefore, the implications of algorithm-driven decisions extend beyond mere numbers to the concept of human dignity. 
	
Although COMPAS attempts to support objective decision-making in the judicial system, its biased statistical profile and the ethical issues surrounding its use make it unreliable for parole considerations. Allowing COMPAS scores to influence parole decisions could depend on systemic biases and diminish the fairness and transparency that should define judicial processes. Instead, a more individualized and transparent approach to assessing relapse risk is preferable. Excluding COMPAS from parole decisions would help preserve standards, ensuring that decisions are made based on a comprehensive understanding of each individual’s circumstances. Thus, in the interests of statistical integrity and ethical commitment, I would advise against including COMPAS in parole decision-making. 
